// Generated by gencpp from file mmdetection_ros/mmdetSrv.msg
// DO NOT EDIT!


#ifndef MMDETECTION_ROS_MESSAGE_MMDETSRV_H
#define MMDETECTION_ROS_MESSAGE_MMDETSRV_H

#include <ros/service_traits.h>


#include <mmdetection_ros/mmdetSrvRequest.h>
#include <mmdetection_ros/mmdetSrvResponse.h>


namespace mmdetection_ros
{

struct mmdetSrv
{

typedef mmdetSrvRequest Request;
typedef mmdetSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mmdetSrv
} // namespace mmdetection_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mmdetection_ros::mmdetSrv > {
  static const char* value()
  {
    return "2cc7b49d11a2a746a7bb9d18f1509c53";
  }

  static const char* value(const ::mmdetection_ros::mmdetSrv&) { return value(); }
};

template<>
struct DataType< ::mmdetection_ros::mmdetSrv > {
  static const char* value()
  {
    return "mmdetection_ros/mmdetSrv";
  }

  static const char* value(const ::mmdetection_ros::mmdetSrv&) { return value(); }
};


// service_traits::MD5Sum< ::mmdetection_ros::mmdetSrvRequest> should match
// service_traits::MD5Sum< ::mmdetection_ros::mmdetSrv >
template<>
struct MD5Sum< ::mmdetection_ros::mmdetSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mmdetection_ros::mmdetSrv >::value();
  }
  static const char* value(const ::mmdetection_ros::mmdetSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mmdetection_ros::mmdetSrvRequest> should match
// service_traits::DataType< ::mmdetection_ros::mmdetSrv >
template<>
struct DataType< ::mmdetection_ros::mmdetSrvRequest>
{
  static const char* value()
  {
    return DataType< ::mmdetection_ros::mmdetSrv >::value();
  }
  static const char* value(const ::mmdetection_ros::mmdetSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mmdetection_ros::mmdetSrvResponse> should match
// service_traits::MD5Sum< ::mmdetection_ros::mmdetSrv >
template<>
struct MD5Sum< ::mmdetection_ros::mmdetSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mmdetection_ros::mmdetSrv >::value();
  }
  static const char* value(const ::mmdetection_ros::mmdetSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mmdetection_ros::mmdetSrvResponse> should match
// service_traits::DataType< ::mmdetection_ros::mmdetSrv >
template<>
struct DataType< ::mmdetection_ros::mmdetSrvResponse>
{
  static const char* value()
  {
    return DataType< ::mmdetection_ros::mmdetSrv >::value();
  }
  static const char* value(const ::mmdetection_ros::mmdetSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MMDETECTION_ROS_MESSAGE_MMDETSRV_H
